all :
	gcc -Wall -Wextra -Werror -fsanitize=address -g3 main.c execute.c libft.a -o micro_ast

valgrind :
	 gcc -Wall -Wextra -Werror -g3 main.c execute.c libft.a -o micro_ast

clean :
	rm -f micro_ast
